JSON_PATH = "static/json/configure.json"
INDEX_TITLE = "EVOLV Newz - Home"
FEEDBACK_TITLE = "EVOLV Newz - Feedback"
ERROR_TITLE = "EVOLV Newz - ERROR"
BASE_URL = "https://news.google.com/rss"
SUCCESS_FEEDBACK_MESSAGE = "Your Feedback is our motivation towards improvement" 
SUCCESS = "success"
CHARACTERS_ERROR_MESSAGE = "Only 250 characters are allowed for the feedback and 50 for Name" 
ERROR = "error"
FEEDBACK_FORM_VALIDATION_ERROR = "Both Name and Feedback are mandatory. Please fill them in"
POST_ON_X_URL = "https://x.com/intent/tweet?text="
GEO_LOCATION = "https://geolocation-db.com/json"